#!/usr/bin/env ruby

# execute commands and report errors
def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

system! 'docker build -t web -f docker.nginx .' # build web server
system! 'docker build -t webpack -f docker.webpack .' # build webpack
system! 'docker run --name web-container -p 8080:8080 -v wwwroot:/wwwroot web' # create both containers
system! 'docker run --name webpack-container -p 35729:35729 -v ~/path/to/code:/app -v /app/node_modules -v wwwroot:/wwwroot webpack'
system! 'docker-compose up --build -d' # run containers
system! 'docker-machine ip default' # find docker IP address
